export const SIGN_IN_USER = 'SIGN_IN_USER';
export const SIGN_OUT_USER = 'SIGN_OUT_USER';

export const SET_MOST_POPULAR_SHOWS = 'SET_MOST_POPULAR_SHOWS';

export const GET_MY_SHOWS = 'GET_MY_SHOWS';
export const ADD_TO_MY_SHOWS = 'ADD_TO_MY_SHOWS';
export const UPDATE_FOUND_SHOWS = 'UPDATE_FOUND_SHOWS';
export const EMPTY_FOUND_SHOWS = 'EMPTY_FOUND_SHOWS';
export const GENERATE_SEASONS = 'GENERATE_SEASONS';

export const GET_WATCHLIST = 'GET_WATCHLIST';
