export const UPDATE_USER = 'UPDATE_USER';
export const SIGN_OUT_USER = 'SIGN_OUT_USER';

export const SET_MOST_POPULAR_SHOWS = 'SET_MOST_POPULAR_SHOWS';

export const SHOW_COLLECTION_GET = 'SHOW_COLLECTION_GET';
export const SHOW_COLLECTION_ADD = 'SHOW_COLLECTION_ADD';
export const SHOW_COLLECTION_DELETE = 'SHOW_COLLECTION_DELETE';
export const UPDATE_FOUND_SHOWS = 'UPDATE_FOUND_SHOWS';
export const EMPTY_FOUND_SHOWS = 'EMPTY_FOUND_SHOWS';
export const GENERATE_SEASONS = 'GENERATE_SEASONS';

export const GET_REWATCHLIST = 'GET_REWATCHLIST';
export const TOGGLE_REWATCHED = 'TOGGLE_REWATCHED';

export const WATCHING_GET = 'WATCHING_GET';
export const WATCHING_ADD = 'WATCHING_ADD';
export const WATCHING_DELETE = 'WATCHING_DELETE';
export const WATCHING_EPISODES_GET = 'WATCHING_EPISODES_GET';
export const WATCHING_TOGGLE_EPISODE_WATCHED = 'WATCHING_TOGGLE_EPISODE_WATCHED';


export const GET_WATCHED = 'GET_WATCHED';

export const GET_WATCHED_MOVIES = 'GET_WATCHED_MOVIES';
export const GET_MOVIE_DETAILS = 'GET_MOVIE_DETAILS';
export const UPDATE_FOUND_MOVIES = 'UPDATE_FOUND_MOVIES';
export const EMPTY_FOUND_MOVIES = 'EMPTY_FOUND_MOVIES';

export const TOAST_MESSAGE = 'TOAST_MESSAGE';
export const TOAST_DISMISS = 'TOAST_DISMISS';
