export const UPDATE_USER = 'UPDATE_USER';
export const SIGN_OUT_USER = 'SIGN_OUT_USER';

export const SET_MOST_POPULAR_SHOWS = 'SET_MOST_POPULAR_SHOWS';

export const SHOW_COLLECTION_GET = 'SHOW_COLLECTION_GET';
export const SHOW_COLLECTION_ADD = 'SHOW_COLLECTION_ADD';
export const SHOW_COLLECTION_DELETE = 'SHOW_COLLECTION_DELETE';
export const UPDATE_FOUND_SHOWS = 'UPDATE_FOUND_SHOWS';
export const EMPTY_FOUND_SHOWS = 'EMPTY_FOUND_SHOWS';

export const WATCHING_GET = 'WATCHING_GET';
export const WATCHING_ADD = 'WATCHING_ADD';
export const WATCHING_DELETE = 'WATCHING_DELETE';
export const WATCHING_EPISODES_GET = 'WATCHING_EPISODES_GET';
export const WATCHING_TOGGLE_EPISODE_WATCHED = 'WATCHING_TOGGLE_EPISODE_WATCHED';
export const WATCHING_ON_UPDATE = 'WATCHING_ON_UPDATE';

export const WATCHED_SHOWS_GET = 'WATCHED_SHOWS_GET';

export const MOVIE_GET = 'MOVIE_GET';
export const MOVIE_COLLECTION_GET = 'MOVIE_COLLECTION_GET';
export const MOVIE_COLLECTION_ADD = 'MOVIE_COLLECTION_ADD';
export const MOVIE_COLLECTION_DELETE = 'MOVIE_COLLECTION_DELETE';
export const MOVIE_DETAILS_GET = 'MOVIE_DETAILS_GET';
export const UPDATE_FOUND_MOVIES = 'UPDATE_FOUND_MOVIES';
export const EMPTY_FOUND_MOVIES = 'EMPTY_FOUND_MOVIES';

export const SEASONS_GET = 'SEASONS_GET';
export const EPISODES_GET = 'EPISODES_GET';
export const LOOKUPS_RESET = 'LOOKUPS_RESET';

export const TOAST_MESSAGE = 'TOAST_MESSAGE';
export const TOAST_DISMISS = 'TOAST_DISMISS';
